version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: restaurant-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=restaurant_system
            - DB_USERNAME=root
            - DB_PASSWORD=root

    db:
        image: mysql:8.0
        container_name: restaurant-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: restaurant_system
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql

    mailhog:
        image: mailhog/mailhog
        container_name: mailhog
        ports:
            - "8025:8025"
            - "1025:1025"

volumes:
    dbdata:
